### ISSUE TITLE
Идея: Ограничить количество элементов при парсинге паблика

### ISSUE THREAD

**Issue by MaxStik** [fn12gl34/vk-scraper#2]
Ограничить по:
Кол-ву постов
Дате публикации (не раньше чем, не позже чем)
Тоже самое по видео/товарам.

**Comment by fn12gl34** [comment]
[implemented](https://github.com/fn12gl34/vk-scraper/commit/a2b697ed2026246bc543c3415143cb9f828f5c4f)
